language: ruby
branches:
  only:
    - master
cache: bundler
sudo: required
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - bin/rake db:setup NO_SUBSCRIPTION_PLANS=true
  - bin/rake
