:verbose: true
:logfile: log/sidekiq.log
:concurrency: <%= ENV['AR_POOL_CONCURRENCY'] || '15' %>
staging:
  :concurrency: <%= ENV['AR_POOL_CONCURRENCY'] || '15' %>
production:
  :concurrency: <%= ENV['AR_POOL_CONCURRENCY'] || '15' %>
:queues:
  - critical
  - default